import 'bloc/k36_bloc.dart';import 'models/k36_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class K36Screen extends StatelessWidget {const K36Screen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<K36Bloc>(create: (context) => K36Bloc(K36State(k36ModelObj: K36Model()))..add(K36InitialEvent()), child: K36Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<K36Bloc, K36State>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgAbstractpatternFullscreenBlack900465x345, height: 465.v, width: 345.h, radius: BorderRadius.circular(32.h)), SizedBox(height: 11.v), _buildAlertMessage(context), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_send".tr.toUpperCase(), onPressed: () {onTapSend(context);}), SizedBox(height: 31.v), Opacity(opacity: 0.5, child: Container(width: 316.h, margin: EdgeInsets.symmetric(horizontal: 14.h), child: Text("msg_lorem_ipsum_dolor3".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.labelMedium))), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
Widget _buildAlertMessage(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 49.h, vertical: 29.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_transfer_sent".tr, style: CustomTextStyles.titleMediumInterWhiteA700), SizedBox(height: 7.v), SizedBox(width: 246.h, child: Text("msg_this_is_a_very_important".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeInterWhiteA700SemiBold))])); } 
/// Navigates to the k27Screen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k27Screen, ); } 
 }
