import 'bloc/k29_bloc.dart';import 'models/k29_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/core/utils/validation_functions.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_drop_down.dart';import 'package:bcc33_s_application1/widgets/custom_elevated_button.dart';import 'package:bcc33_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class K29Screen extends StatelessWidget {K29Screen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<K29Bloc>(create: (context) => K29Bloc(K29State(k29ModelObj: K29Model()))..add(K29InitialEvent()), child: K29Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: 361.h, margin: EdgeInsets.fromLTRB(16.h, 4.v, 16.h, 5.v), padding: EdgeInsets.all(24.h), decoration: AppDecoration.outlineBlack90026.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(width: 313.h, padding: EdgeInsets.symmetric(vertical: 1.v), decoration: AppDecoration.outlineBlueGray, child: Text("lbl_new_beneficiary".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapBankDetails(context);}, child: Container(decoration: AppDecoration.outlineBlueGray, child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_bank_details".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 15.v), BlocSelector<K29Bloc, K29State, K29Model?>(selector: (state) => state.k29ModelObj, builder: (context, k29ModelObj) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 16.h, 12.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(8.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_choose_country".tr, items: k29ModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v), onChanged: (value) {context.read<K29Bloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 8.v), _buildKingTChalla(context), SizedBox(height: 8.v), _buildKingTChalla1(context), SizedBox(height: 24.v)]))), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapBankDetails1(context);}, child: Container(decoration: AppDecoration.outlineBlueGray, child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_pesonal_details".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 15.v), _buildFirstName(context), SizedBox(height: 8.v), _buildLastName(context), SizedBox(height: 8.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildCity(context), _buildZipcode(context)]), SizedBox(height: 24.v)]))), SizedBox(height: 24.v), _buildAddBeneficiary(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcons1, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_transfers".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildKingTChalla(BuildContext context) { return BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.kingTChallaController, builder: (context, kingTChallaController) {return CustomTextFormField(controller: kingTChallaController, hintText: "lbl_iban".tr, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}); } 
/// Section Widget
Widget _buildKingTChalla1(BuildContext context) { return BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.kingTChallaController1, builder: (context, kingTChallaController1) {return CustomTextFormField(controller: kingTChallaController1, hintText: "lbl_swift".tr, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}); } 
/// Section Widget
Widget _buildFirstName(BuildContext context) { return BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.firstNameController, builder: (context, firstNameController) {return CustomTextFormField(controller: firstNameController, hintText: "lbl_first_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}); } 
/// Section Widget
Widget _buildLastName(BuildContext context) { return BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.lastNameController, builder: (context, lastNameController) {return CustomTextFormField(controller: lastNameController, hintText: "lbl_last_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}); } 
/// Section Widget
Widget _buildCity(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 4.h), child: BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.cityController, builder: (context, cityController) {return CustomTextFormField(controller: cityController, hintText: "lbl_city".tr, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}))); } 
/// Section Widget
Widget _buildZipcode(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 4.h), child: BlocSelector<K29Bloc, K29State, TextEditingController?>(selector: (state) => state.zipcodeController, builder: (context, zipcodeController) {return CustomTextFormField(controller: zipcodeController, hintText: "lbl_zip_code".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: theme.colorScheme.onPrimaryContainer);}))); } 
/// Section Widget
Widget _buildAddBeneficiary(BuildContext context) { return CustomElevatedButton(text: "lbl_add_beneficiary".tr.toUpperCase(), rightIcon: Container(margin: EdgeInsets.only(left: 30.h), decoration: BoxDecoration(borderRadius: BorderRadius.circular(8.h)), child: CustomImageView(imagePath: ImageConstant.imgIconsGray90001, height: 32.adaptSize, width: 32.adaptSize))); } 
/// Navigates to the k30Screen when the action is triggered.
onTapBankDetails(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k30Screen, ); } 
/// Navigates to the k30Screen when the action is triggered.
onTapBankDetails1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k30Screen, ); } 
 }
