import '../k53_screen/widgets/my_item_widget.dart';import 'bloc/k53_bloc.dart';import 'models/k53_model.dart';import 'models/my_item_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_icon_button.dart';import 'package:bcc33_s_application1/widgets/custom_outlined_button.dart';import 'package:bcc33_s_application1/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class K53Screen extends StatelessWidget {const K53Screen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<K53Bloc>(create: (context) => K53Bloc(K53State(k53ModelObj: K53Model()))..add(K53InitialEvent()), child: K53Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 20.v), child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 5.v), child: Column(children: [BlocSelector<K53Bloc, K53State, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "msg_search_team_member".tr);}), SizedBox(height: 24.v), _buildCategoryTags(context), SizedBox(height: 24.v), Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillOnPrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildMY(context), Container(padding: EdgeInsets.only(top: 24.v, bottom: 23.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildLA(context), Padding(padding: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_leia_amidala".tr, style: theme.textTheme.titleSmall), SizedBox(height: 1.v), Text("lbl_payer".tr, style: theme.textTheme.titleSmall), SizedBox(height: 17.v), Container(margin: EdgeInsets.only(left: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.circleBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIcons14, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_reveiew".tr, style: theme.textTheme.titleSmall))])), SizedBox(height: 19.v), Text("msg_has_initiated_a".tr, style: theme.textTheme.titleSmall)]))])), Container(padding: EdgeInsets.only(top: 24.v, bottom: 23.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Row(children: [_buildDD(context), Padding(padding: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 4.v), child: Column(children: [Text("lbl_din_djarin".tr, style: theme.textTheme.titleSmall), Text("lbl_employee".tr, style: theme.textTheme.titleSmall)]))])), Container(padding: EdgeInsets.only(top: 24.v, bottom: 23.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Row(children: [_buildDG(context), Padding(padding: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_din_grogu".tr, style: theme.textTheme.titleSmall), Text("lbl_viewer".tr, style: theme.textTheme.titleSmall)]))]))]))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcons1, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_team".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildCategoryTags(BuildContext context) { return GestureDetector(onTap: () {onTapCategoryTags(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 101.h, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 11.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_admin".tr, style: theme.textTheme.titleSmall)), Container(width: 101.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 9.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_payer".tr, style: theme.textTheme.titleSmall)), Container(width: 101.h, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 11.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_viewer".tr, style: theme.textTheme.titleSmall)), Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.fillOnPrimary, child: CustomImageView(imagePath: ImageConstant.imgIcons40)))])); } 
/// Section Widget
Widget _buildMY(BuildContext context) { return BlocSelector<K53Bloc, K53State, K53Model?>(selector: (state) => state.k53ModelObj, builder: (context, k53ModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: k53ModelObj?.myItemList.length ?? 0, itemBuilder: (context, index) {MyItemModel model = k53ModelObj?.myItemList[index] ?? MyItemModel(); return MyItemWidget(model, onTapCellGeneral: () {onTapCellGeneral(context);});});}); } 
/// Section Widget
Widget _buildLA(BuildContext context) { return CustomOutlinedButton(width: 56.h, text: "lbl_la".tr, margin: EdgeInsets.only(bottom: 71.v), buttonTextStyle: CustomTextStyles.titleSmallPrimary); } 
/// Section Widget
Widget _buildDD(BuildContext context) { return CustomOutlinedButton(width: 56.h, text: "lbl_dd".tr, buttonTextStyle: CustomTextStyles.titleSmallPrimary); } 
/// Section Widget
Widget _buildDG(BuildContext context) { return CustomOutlinedButton(width: 56.h, text: "lbl_dg".tr, buttonTextStyle: CustomTextStyles.titleSmallPrimary); } 
/// Navigates to the tabContainerScreen when the action is triggered.
onTapCellGeneral(BuildContext context) { NavigatorService.pushNamed(AppRoutes.tabContainerScreen); } 
/// Navigates to the tabContainer1Screen when the action is triggered.
onTapCategoryTags(BuildContext context) { NavigatorService.pushNamed(AppRoutes.tabContainer1Screen, ); } 
 }
