import '../k51_screen/widgets/bw2_item_widget.dart';import 'bloc/k51_bloc.dart';import 'models/bw2_item_model.dart';import 'models/k51_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/core/utils/validation_functions.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_drop_down.dart';import 'package:bcc33_s_application1/widgets/custom_elevated_button.dart';import 'package:bcc33_s_application1/widgets/custom_search_view.dart';import 'package:bcc33_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class K51Screen extends StatelessWidget {K51Screen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<K51Bloc>(create: (context) => K51Bloc(K51State(k51ModelObj: K51Model()))..add(K51InitialEvent()), child: K51Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v), child: Column(children: [BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "msg_search_beneficiary2".tr);}), SizedBox(height: 32.v), Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillOnPrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildCellGeneral(context), Container(padding: EdgeInsets.only(top: 24.v, bottom: 23.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_bank_details2".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 7.v), BlocSelector<K51Bloc, K51State, K51Model?>(selector: (state) => state.k51ModelObj, builder: (context, k51ModelObj) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 16.h, 12.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(8.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_england".tr, items: k51ModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v), borderDecoration: DropDownStyleHelper.fillOnPrimary, fillColor: theme.colorScheme.onPrimary.withOpacity(1), onChanged: (value) {context.read<K51Bloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 8.v), _buildKingTChalla(context), SizedBox(height: 8.v), _buildKingTChalla1(context), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Text("msg_personal_details".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 6.v), _buildKingTChalla2(context), SizedBox(height: 8.v), _buildKingTChalla3(context), SizedBox(height: 8.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildKingTChalla4(context), _buildZipcode(context)]), SizedBox(height: 32.v), _buildSend(context)])), SizedBox(height: 24.v), _buildBW(context)])))), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcons1, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_beneficiaries2".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildCellGeneral(BuildContext context) { return BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.cellGeneralController, builder: (context, cellGeneralController) {return CustomTextFormField(controller: cellGeneralController, hintText: "lbl_new_beneficiary2".tr, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 10.v, 27.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgIcons38, height: 27.v, width: 33.h)), prefixConstraints: BoxConstraints(maxHeight: 72.v), contentPadding: EdgeInsets.only(top: 27.v, right: 30.h, bottom: 27.v), borderDecoration: TextFormFieldStyleHelper.outlineOnPrimaryContainer1, filled: false);}); } 
/// Section Widget
Widget _buildKingTChalla(BuildContext context) { return BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.kingTChallaController, builder: (context, kingTChallaController) {return CustomTextFormField(controller: kingTChallaController, hintText: "msg_gb80barc20040139494817".tr);}); } 
/// Section Widget
Widget _buildKingTChalla1(BuildContext context) { return BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.kingTChallaController1, builder: (context, kingTChallaController1) {return CustomTextFormField(controller: kingTChallaController1, hintText: "lbl_mi6ahms".tr);}); } 
/// Section Widget
Widget _buildKingTChalla2(BuildContext context) { return BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.kingTChallaController2, builder: (context, kingTChallaController2) {return CustomTextFormField(controller: kingTChallaController2, hintText: "lbl_james".tr);}); } 
/// Section Widget
Widget _buildKingTChalla3(BuildContext context) { return BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.kingTChallaController3, builder: (context, kingTChallaController3) {return CustomTextFormField(controller: kingTChallaController3, hintText: "lbl_bond".tr);}); } 
/// Section Widget
Widget _buildKingTChalla4(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 4.h), child: BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.kingTChallaController4, builder: (context, kingTChallaController4) {return CustomTextFormField(controller: kingTChallaController4, hintText: "lbl_skyfall".tr);}))); } 
/// Section Widget
Widget _buildZipcode(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 4.h), child: BlocSelector<K51Bloc, K51State, TextEditingController?>(selector: (state) => state.zipcodeController, builder: (context, zipcodeController) {return CustomTextFormField(controller: zipcodeController, hintText: "lbl_zip_code".tr, hintStyle: CustomTextStyles.titleSmallPrimary, textInputAction: TextInputAction.done, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}))); } 
/// Section Widget
Widget _buildSend(BuildContext context) { return CustomElevatedButton(text: "lbl_send".tr.toUpperCase()); } 
/// Section Widget
Widget _buildBW(BuildContext context) { return Expanded(child: BlocSelector<K51Bloc, K51State, K51Model?>(selector: (state) => state.k51ModelObj, builder: (context, k51ModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: k51ModelObj?.bw2ItemList.length ?? 0, itemBuilder: (context, index) {Bw2ItemModel model = k51ModelObj?.bw2ItemList[index] ?? Bw2ItemModel(); return Bw2ItemWidget(model, onTapCellGeneral: () {onTapCellGeneral(context);});});})); } 
/// Navigates to the k52Screen when the action is triggered.
onTapCellGeneral(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k52Screen, ); } 
 }
