import '../k50_screen/widgets/bw1_item_widget.dart';import 'bloc/k50_bloc.dart';import 'models/bw1_item_model.dart';import 'models/k50_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_search_view.dart';import 'package:bcc33_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class K50Screen extends StatelessWidget {const K50Screen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<K50Bloc>(create: (context) => K50Bloc(K50State(k50ModelObj: K50Model()))..add(K50InitialEvent()), child: K50Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v), child: Column(children: [BlocSelector<K50Bloc, K50State, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "msg_search_beneficiary2".tr);}), SizedBox(height: 32.v), Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillOnPrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [BlocSelector<K50Bloc, K50State, TextEditingController?>(selector: (state) => state.cellGeneralController, builder: (context, cellGeneralController) {return CustomTextFormField(controller: cellGeneralController, hintText: "lbl_new_beneficiary2".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 10.v, 27.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary27x33, height: 27.v, width: 33.h)), prefixConstraints: BoxConstraints(maxHeight: 72.v), contentPadding: EdgeInsets.only(top: 27.v, right: 30.h, bottom: 27.v), borderDecoration: TextFormFieldStyleHelper.outlineOnPrimaryContainer1, filled: false);}), _buildBW(context), SizedBox(height: 24.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(decoration: AppDecoration.outlinePrimary5.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 15.v), Text("lbl_fs".tr, style: theme.textTheme.titleSmall), SizedBox(height: 3.v), CustomImageView(imagePath: ImageConstant.imgFlags12x12, height: 12.adaptSize, width: 12.adaptSize, radius: BorderRadius.circular(6.h), alignment: Alignment.centerRight)])), Padding(padding: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_franziska_szab".tr, style: theme.textTheme.titleSmall), SizedBox(height: 1.v), Text("msg_account_ending_with9".tr, style: theme.textTheme.titleSmall)]))])), Container(height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(left: 31.h, top: 8.v, bottom: 8.v), decoration: AppDecoration.outlinePrimary7.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomImageView(imagePath: ImageConstant.imgIcons29, height: 32.adaptSize, width: 32.adaptSize, radius: BorderRadius.circular(16.h), alignment: Alignment.center, onTap: () {onTapImgIcons(context);}))]), SizedBox(height: 24.v)])))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcons1, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_beneficiaries2".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildBW(BuildContext context) { return Expanded(child: BlocSelector<K50Bloc, K50State, K50Model?>(selector: (state) => state.k50ModelObj, builder: (context, k50ModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: k50ModelObj?.bw1ItemList.length ?? 0, itemBuilder: (context, index) {Bw1ItemModel model = k50ModelObj?.bw1ItemList[index] ?? Bw1ItemModel(); return Bw1ItemWidget(model, onTapImgJNKK: () {onTapImgJNKK(context);});});})); } 
/// Navigates to the k32Screen when the action is triggered.
onTapImgJNKK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k32Screen); } 
/// Navigates to the k32Screen when the action is triggered.
onTapImgIcons(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k32Screen, ); } 
 }
