import '../k58_screen/widgets/cancelled_item_widget.dart';import 'bloc/k58_bloc.dart';import 'models/cancelled_item_model.dart';import 'models/k58_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_search_view.dart';import 'package:bcc33_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class K58Screen extends StatelessWidget {const K58Screen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<K58Bloc>(create: (context) => K58Bloc(K58State(k58ModelObj: K58Model()))..add(K58InitialEvent()), child: K58Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v), child: Column(children: [BlocSelector<K58Bloc, K58State, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "msg_search_amount_beneficiary".tr);}), SizedBox(height: 24.v), _buildCategoryTags(context), SizedBox(height: 24.v), Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillOnPrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [BlocSelector<K58Bloc, K58State, TextEditingController?>(selector: (state) => state.cellGeneralController, builder: (context, cellGeneralController) {return CustomTextFormField(controller: cellGeneralController, hintText: "msg_new_payment_link".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 30.v, 27.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgIcons21, height: 27.v, width: 33.h)), prefixConstraints: BoxConstraints(maxHeight: 96.v), contentPadding: EdgeInsets.only(top: 39.v, right: 30.h, bottom: 39.v), borderDecoration: TextFormFieldStyleHelper.outlineOnPrimaryContainer1, filled: false);}), _buildCancelled(context)])))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcons1, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_payment_links2".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v))]); } 
/// Section Widget
Widget _buildCategoryTags(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 115.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 11.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_paid".tr, style: theme.textTheme.titleSmall)), Container(width: 115.h, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 9.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_pending".tr, style: theme.textTheme.titleSmall)), Container(width: 115.h, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 11.v), decoration: AppDecoration.outlineGray900033.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("lbl_cancelled".tr, style: theme.textTheme.titleSmall))]); } 
/// Section Widget
Widget _buildCancelled(BuildContext context) { return Expanded(child: BlocSelector<K58Bloc, K58State, K58Model?>(selector: (state) => state.k58ModelObj, builder: (context, k58ModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: k58ModelObj?.cancelledItemList.length ?? 0, itemBuilder: (context, index) {CancelledItemModel model = k58ModelObj?.cancelledItemList[index] ?? CancelledItemModel(); return CancelledItemWidget(model, onTapRow: () {onTapRow(context);});});})); } 
/// Navigates to the k60Screen when the action is triggered.
onTapRow(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k60Screen, ); } 
 }
