import '../k26_screen/widgets/bigctas1_item_widget.dart';import '../k26_screen/widgets/icons1_item_widget.dart';import 'bloc/k26_bloc.dart';import 'models/bigctas1_item_model.dart';import 'models/icons1_item_model.dart';import 'models/k26_model.dart';import 'package:bcc33_s_application1/core/app_export.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_title.dart';import 'package:bcc33_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:bcc33_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:bcc33_s_application1/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class K26Screen extends StatelessWidget {const K26Screen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<K26Bloc>(create: (context) => K26Bloc(K26State(k26ModelObj: K26Model()))..add(K26InitialEvent()), child: K26Screen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), decoration: AppDecoration.bGDark, child: Column(children: [Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Column(mainAxisSize: MainAxisSize.min, children: [Expanded(child: SizedBox(width: double.maxFinite, child: Container(decoration: AppDecoration.outlineBlueGray, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_available_funds".tr, style: theme.textTheme.titleSmall), SizedBox(height: 15.v), _buildIcons(context), SizedBox(height: 24.v)])))), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_beneficiaries".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 15.v), GestureDetector(onTap: () {onTapCellInfo(context);}, child: Container(decoration: AppDecoration.outlineBluegray900.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(margin: EdgeInsets.only(right: 12.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomIconButton(height: 64.adaptSize, width: 64.adaptSize, padding: EdgeInsets.all(13.h), child: CustomImageView(imagePath: ImageConstant.imgAvatars)), Padding(padding: EdgeInsets.only(left: 16.h, top: 14.v, bottom: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_742748510_45545613".tr, style: theme.textTheme.titleSmall), SizedBox(height: 1.v), Text("lbl_jnkk_ltd".tr, style: theme.textTheme.titleSmall)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgIconsWhiteA700, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 20.v))])))), SizedBox(height: 16.v), _buildBigCTAS(context)])), SizedBox(height: 14.v), CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgIcons16)), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 96.v, title: AppbarTitle(text: "lbl_transfers".tr, margin: EdgeInsets.only(left: 40.h)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgAvatarsGray900, margin: EdgeInsets.symmetric(horizontal: 16.h))]); } 
/// Section Widget
Widget _buildIcons(BuildContext context) { return Expanded(child: BlocSelector<K26Bloc, K26State, K26Model?>(selector: (state) => state.k26ModelObj, builder: (context, k26ModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: k26ModelObj?.icons1ItemList.length ?? 0, itemBuilder: (context, index) {Icons1ItemModel model = k26ModelObj?.icons1ItemList[index] ?? Icons1ItemModel(); return Icons1ItemWidget(model);});})); } 
/// Section Widget
Widget _buildBigCTAS(BuildContext context) { return Container(height: 160.v, decoration: AppDecoration.outlineGray3003, child: BlocSelector<K26Bloc, K26State, K26Model?>(selector: (state) => state.k26ModelObj, builder: (context, k26ModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: k26ModelObj?.bigctas1ItemList.length ?? 0, itemBuilder: (context, index) {Bigctas1ItemModel model = k26ModelObj?.bigctas1ItemList[index] ?? Bigctas1ItemModel(); return Bigctas1ItemWidget(model);});})); } 
/// Navigates to the k32Screen when the action is triggered.
onTapCellInfo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k32Screen, ); } 
 }
